### ISSUE TITLE
ci: initial configuration

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-auth-vomsproxy#6]
Introduce Travis CI.

It is dangerous to push images to Docker Hub after each commit if the image is not tested. 

The CI should:
- build the image and exit if the build has troubles;
- ideally, launch tiny test to see whether the functionality is OK.

**Comment by alintulu** [comment]
You could maybe also do it with Github actions? That would save the need to build the image twice, once for Travis testing and once with actions for deploying it. 

With actions you could define three jobs

1. Build the image
2. Test the image
3. Push the image to registry

Step 3 would only be triggered on success of Step 1 and Step 2.

**Comment by tiborsimko** [comment]
Yes, using GitHub Actions will also nicely do. (BTW Docker Hub could also trigger builds, and GitHub could also hold image repositories, but let's not explore going that way yet...)

**Comment by clelange** [comment]
GitHub has quite some restrictions on image size, so I don't think keeping the image here rather than on Docker Hub is a viable option at the moment.

I'm a bit afraid that all what you're trying to achieve here is possible and already done on CERN GitLab, and we're wasting our time implementing the same thing on GitHub again with unknown potential complications. If further tests are required, I would rather have this repository be a mirror of what is on GitLab or the other way round, but have the full CI on CERN GitLab and also push to Docker Hub from there.

**Comment by tiborsimko** [comment]
Closing this old issue; the first CI functionality was implemented in #4 and later made to behave similarly as the other REANA components in #14.
